### ISSUE TITLE
Roadmap (2019 February)

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS-forecasting#3]
## Reproduce Ward et al. 2014 Results [repo](https://github.com/eric-ward/complexity-costly)
- [ ] gather remaining datasets (there might be a few datasets that are publicly available that aren't included for release with the original repo)
- [x] implement remainder of methods with tests
- [x] add code to transform and summarize results

## Expand / correct the methods
- [x] permutation entropy
- [x] corrected (?) EDM methods
- [ ] GP-EDM methods

## Expand list of datasets
- [ ] refer to ongoing work in https://github.com/weecology/MATSS/issues/52
- [x] GPDD (global population dynamics database)
- [x] Biotime
- [ ] CDC, epidemiological time series

## Produce manuscript
